# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Atlas-Vim
description: Pre-Configure Vim for Atlas(Sheridan) Student
tagline: Atlas-Vim , it have everything for you
url: localhost:4000

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: Julio Tain Sueiras
  email: juliosueiras@gmail.com
  bio: I am programming who love archlinux, vim , and speak mandarin
  twitter: twitter.com/juliosueiras

# general setting for Jekyll
googleAnalytics: UA-XXXXX-X

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: pygments
baseurl: /atlas-vim
